/*
 * Generated by ./generate.pl
 * Unicode version 17.0.0
 * https://github.com/detomon/unicode-table
 */

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include <stdint.h>

/**
 * Maximum allowed Unicode value.
 */
#define UT_MAX_VALUE 0x10FFFF

/**
 * Flags for determining character type.
 */
typedef enum {
	UT_FLAG_LETTER       = 1 << 0,  ///< Is letter.
	UT_FLAG_UPPERCASE    = 1 << 1,  ///< Is uppercase letter.
	UT_FLAG_LOWERCASE    = 1 << 2,  ///< Is lowercase letter.
	UT_FLAG_TITLECASE    = 1 << 3,  ///< Is titlecase letter.
	UT_FLAG_SPACE        = 1 << 4,  ///< Is space character.
	UT_FLAG_LINEBREAK    = 1 << 5,  ///< Is linebreak.
	UT_FLAG_PUNCTUATION  = 1 << 6,  ///< Is punctuation character.
	UT_FLAG_DIGIT        = 1 << 7,  ///< Is digit character.
	UT_FLAG_NUMBER       = 1 << 8,  ///< Is number character.
	UT_FLAG_FRACTION     = 1 << 9,  ///< Is fraction character.
	UT_FLAG_CONTROL      = 1 << 10, ///< Is control character.
	UT_FLAG_SYMBOL       = 1 << 11, ///< Is symbol.
	UT_FLAG_OTHER        = 1 << 12, ///< Other character.
	UT_FLAG_UPPER_EXPANDS = 1 << 13, ///< Uppercase expands to multiple characters.
	UT_FLAG_LOWER_EXPANDS = 1 << 14, ///< Lowercase expands to multiple characters.
	UT_FLAG_TITLE_EXPANDS = 1 << 15, ///< Titlecase expands to multiple characters.
	UT_FLAG_CASE_EXPANDS = UT_FLAG_UPPER_EXPANDS | UT_FLAG_LOWER_EXPANDS | UT_FLAG_TITLE_EXPANDS, ///< Some case expands to multiple characters.
} UTFlag;

/**
 * Character categories.
 */
typedef enum {
	UT_CATEGORY_INVALID,                    ///<
	UT_CATEGORY_LETTER_UPPERCASE,           ///< Lu
	UT_CATEGORY_LETTER_LOWERCASE,           ///< Ll
	UT_CATEGORY_LETTER_TITLECASE,           ///< Lt
	UT_CATEGORY_LETTER_MODIFIER,            ///< Lm
	UT_CATEGORY_LETTER_OTHER,               ///< Lo
	UT_CATEGORY_MARK_NONSPACING,            ///< Mn
	UT_CATEGORY_MARK_SPACING_COMBINING,     ///< Mc
	UT_CATEGORY_MARK_ENCLOSING,             ///< Me
	UT_CATEGORY_NUMBER_DECIMAL_DIGIT,       ///< Nd
	UT_CATEGORY_NUMBER_LETTER,              ///< Nl
	UT_CATEGORY_NUMBER_OTHER,               ///< No
	UT_CATEGORY_PUNCTUATION_CONNECTOR,      ///< Pc
	UT_CATEGORY_PUNCTUATION_DASH,           ///< Pd
	UT_CATEGORY_PUNCTUATION_OPEN,           ///< Ps
	UT_CATEGORY_PUNCTUATION_CLOSE,          ///< Pe
	UT_CATEGORY_PUNCTUATION_INITIAL_QUOTE,  ///< Pi
	UT_CATEGORY_PUNCTUATION_FINAL_QUOTE,    ///< Pf
	UT_CATEGORY_PUNCTUATION_OTHER,          ///< Po
	UT_CATEGORY_SYMBOL_MATH,                ///< Sm
	UT_CATEGORY_SYMBOL_CURRENCY,            ///< Sc
	UT_CATEGORY_SYMBOL_MODIFIER,            ///< Sk
	UT_CATEGORY_SYMBOL_OTHER,               ///< So
	UT_CATEGORY_SEPARATOR_SPACE,            ///< Zs
	UT_CATEGORY_SEPARATOR_LINE,             ///< Zl
	UT_CATEGORY_SEPARATOR_PARAGRAPH,        ///< Zp
	UT_CATEGORY_OTHER_CONTROL,              ///< Cc
	UT_CATEGORY_OTHER_FORMAT,               ///< Cf
	UT_CATEGORY_OTHER_SURROGATE,            ///< Cs
	UT_CATEGORY_OTHER_PRIVATE_USE,          ///< Co
	UT_CATEGORY_OTHER_NOT_ASSIGNED,         ///< Cn
} UTCategory;

/**
 * Case variant index usable for `cases` field in `UTInfo`.
 */
typedef enum {
	UT_CASE_UPPER = 0, ///< Index for uppercase variant.
	UT_CASE_LOWER = 1, ///< Index for lowercase variant.
	UT_CASE_TITLE = 2, ///< Index for titlecase variant.
} UTCase;

/**
 * A Unicode character value.
 */
typedef uint32_t UTGlyph;

/**
 * Character info.
 */
typedef struct {
	uint32_t flags;    ///< Combination of `UTFlag`.
	uint32_t category; ///< One of `UTCategory`.
	int32_t cases[3];  ///< Distance to case variant. Indexable with `UTCase`.
	union {
		int64_t num;      ///< Number value if `flags & UT_FLAG_NUMBER`.
		char const* frac; ///< Fraction string if `flags & UT_FLAG_FRACTION`.
	};
} UTInfo;

/**
 * Helper struct for reading special case-folding sequences.
 */
typedef struct {
	UTGlyph count;    ///< Number of characters.
	UTGlyph glyphs[]; ///< Sequence of characters.
} UTSpecialCase;

/**
 * Table sizes.
 */
#define UT_INFO_TABLE_SIZE 539
#define UT_PAGE_INDEX_TABLE_SIZE 4352
#define UT_INFO_INDEX_TABLE_SIZE 163
#define UT_SPECIAL_CASES_TABLE_SIZE 485
#define UT_CATEGORY_NAMES_TABLE_SIZE 31

/**
 * Character information indexable with values from UTInfoIndex.
 */
extern UTInfo const UTInfos[UT_INFO_TABLE_SIZE];

/**
 * Character page lookup table.
 */
extern uint8_t const UTPageIndex[UT_PAGE_INDEX_TABLE_SIZE];

/**
 * Character lookup table.
 */
extern uint16_t const UTInfoIndex[UT_INFO_INDEX_TABLE_SIZE][256];

/**
 * Special case-folding sequences.
 */
extern UTGlyph const UTSpecialCases[UT_SPECIAL_CASES_TABLE_SIZE];

/**
 * Category name indexable with `UTCategory`.
 */
extern char const* const UTCategoryNames[UT_CATEGORY_NAMES_TABLE_SIZE];

/**
 * Lookup character by value.
 *
 * @param glyph A Unicode character value.
 * @return Character info.
 */
static inline UTInfo const* UTLookupGlyph(UTGlyph glyph) {
	if (glyph > UT_MAX_VALUE) {
		return &UTInfos[0];
	}

	const uint8_t page = UTPageIndex[glyph >> 8];
	const uint16_t offset = UTInfoIndex[page][glyph & 0xFF];

	return &UTInfos[offset];
}

/**
 * Get special case-folding sequence of character.
 *
 * @param info Character information of @p glyph.
 * @param variant Case variant.
 * @return Case-folding sequence or `NULL` if none exists for given case variant.
 */
static inline UTSpecialCase const* UTGetSpecialCase(UTInfo const* info, UTCase variant) {
	if (info->flags & (UT_FLAG_UPPER_EXPANDS << variant)) {
		return (UTSpecialCase const*) &UTSpecialCases[info->cases[variant]];
	}

	return NULL;
}

/**
 * Minimum valid range for sequence sizes. Value is expressed as shift.
 *
 * ```
 * 0XXXXXXX
 * 110XXXXX 10XXXXXX                                      (1 << 7)
 * 1110XXXX 10XXXXXX 10XXXXXX                             (1 << 11)
 * 11110XXX 10XXXXXX 10XXXXXX 10XXXXXX                    (1 << 16)
 * 111110XX 10XXXXXX 10XXXXXX 10XXXXXX 10XXXXXX           (1 << 21)
 * 1111110X 10XXXXXX 10XXXXXX 10XXXXXX 10XXXXXX 10XXXXXX  (1 << 26)
 * ```
 */
#define UT_VALID_RANGES (\
	(7UL << 5) | \
	(11UL << 10) | \
	(16UL << 15) | \
	(21UL << 20) | \
	(26UL << 25))

/**
 * Get minimum valid glyph value for UTF-8 sequence with @p length continuation bytes.
 *
 * @param length Number of UTF-8 continuation bytes.
 * @return Minimum valid glyph value.
 */
static inline UTGlyph UTMinValidGlyph(uint32_t length) {
	return 1U << ((UT_VALID_RANGES >> (length * 5)) & 0x1F);
}

#ifdef __cplusplus
}
#endif
